use_frameworks!

platform :ios, '8.0'

target 'TZSupreMarkHome_Example' do
  pod 'TZSupreMarkHome', :path => '../'

  target 'TZSupreMarkHome_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
